I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /cm/shared/openmind/cuda/7.5/lib64:/cm/shared/openmind/cuda/7.5/lib
I tensorflow/stream_executor/cuda/cuda_dnn.cc:2092] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
print sys.argv = ['main_nn.py', '2707736', '9', 'HBF1_6_multiple_S_random_HP_test', 'True', 'om_results', 'multiple_S_test', '6']
len(sys.argv) = 8
print argv = ['main_nn.py', '2707736', '9', 'HBF1_6_multiple_S_random_HP_test', 'True', 'om_results', 'multiple_S_test', '6']
len(argv) = 8
['main_nn.py', '2707736', '9', 'HBF1_6_multiple_S_random_HP_test', 'True', 'om_results', 'multiple_S_test', '6']
2.1
prefix=om_results,slurm_jobid=2707736,slurm_array_task_id=9,job_number=HBF1_6_multiple_S_random_HP_test
==> tensorboard_data_dump_train:  /tmp/mdl_logs/train
==> tensorboard_data_dump_test:  /tmp/mdl_logs/test
mdl_save True
Traceback (most recent call last):
  File "main_nn.py", line 84, in <module>
    shutil.rmtree(tensorboard_data_dump_test)
  File "/home/brando90/envs/tensorflow/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/home/brando90/envs/tensorflow/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 2] No such file or directory: '/tmp/mdl_logs/test/events.out.tfevents.1468867174.node005.cm.cluster'
